const COMPRESSOR_CONSTANT = "COMPRESSOR";
const POWER_GENERATOR_CONSTANT = "POWER_GENERATOR";

module.exports = {
    COMPRESSOR_CONSTANT: COMPRESSOR_CONSTANT,
    POWER_GENERATOR_CONSTANT: POWER_GENERATOR_CONSTANT
};